plugins {
    id 'java'
    id 'idea'
    id 'io.franzbecker.gradle-lombok' version '2.0'
    id 'org.springframework.boot' version '2.1.1.RELEASE'
    id 'io.spring.dependency-management' version '1.0.6.RELEASE'
}

group 'haggis-and-chips'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

lombok {
    version = '1.18.4'
    sha256 = "39f3922deb679b1852af519eb227157ef2dd0a21eec3542c8ce1b45f2df39742"
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:2.1.1.RELEASE'
    }
}

dependencies {

    compile 'org.springframework.boot:spring-boot-starter'
    compile 'org.springframework:spring-web'

    compile 'com.fasterxml.jackson.core:jackson-databind'

    testCompile 'junit:junit'
}
