buildscript {
    ext {
        springBootVersion = '4.1.1'
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'haggis-and-chips'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.7'
    modules = ['javafx.controls']
}

repositories {
    mavenCentral()
}

tasks.named('bootRun') {
    javaLauncher = javaToolchains.launcherFor(java.toolchain)
}

dependencies {

    implementation platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")

    implementation 'org.springframework.boot:spring-boot-starter'

    implementation 'com.fasterxml.jackson.core:jackson-databind'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'
}
